<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 F:\droneclub\3D_assets\unt aero plane thing.glb --transform
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/unt aero plane thing-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Canopy_2.geometry}
      material={gltf.materials['Material.001']}
      position={[0.07, 0.2, 2.78]}
      rotation={[2.55, 1.55, 2.02]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Elev1L.geometry}
      material={gltf.materials.white}
      position={[1.06, -0.62, -3.42]}
      rotation={[3.04, -0.03, -1.56]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Elev2R.geometry}
      material={gltf.materials.white}
      position={[-1.23, -0.6, -3.37]}
      rotation={[3.04, -0.03, 1.58]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon1L.geometry}
      material={gltf.materials.wing}
      position={[0.95, 0.06, 0.41]}
      rotation={[3.07, -0.03, -1.56]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon1R.geometry}
      material={gltf.materials.wing}
      position={[-0.9, 0.08, 0.46]}
      rotation={[3.07, -0.02, 1.58]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon2L.geometry}
      material={gltf.materials.white}
      position={[2.19, 0.06, 0.45]}
      rotation={[3.07, -0.03, -1.57]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon2R.geometry}
      material={gltf.materials.white}
      position={[-2.15, 0.1, 0.58]}
      rotation={[3.08, -0.03, 1.58]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon3L.geometry}
      material={gltf.materials.white}
      position={[3.68, 0.17, 0.35]}
      rotation={[3.07, -0.03, -1.57]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Flaperon3R.geometry}
      material={gltf.materials.white}
      position={[-3.63, 0.25, 0.56]}
      rotation={[3.07, -0.03, 1.59]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Fus2_wo_LG.geometry}
      material={gltf.materials.wing}
      position={[0.06, -0.12, 2.74]}
      rotation={[1.47, -0.01, -0.03]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Fus3.geometry}
      material={gltf.materials.wing}
      position={[-0.01, -0.32, 0.05]}
      rotation={[1.47, -0.01, -0.03]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Fus4.geometry}
      material={gltf.materials.wing}
      position={[-0.04, -0.38, -1.09]}
      rotation={[1.47, -0.01, -0.03]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Fus5.geometry}
      material={gltf.materials.wing}
      position={[-0.09, -0.54, -2.61]}
      rotation={[1.47, -0.01, 3.11]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Guide.geometry}
      material={gltf.nodes.Guide.material}
      position={[0.02, -0.19, 1.31]}
      rotation={[2.87, -0.03, 0]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.HTP_L.geometry}
      material={gltf.materials.wing}
      position={[1, -0.61, -2.97]}
      rotation={[3.06, -0.03, -1.56]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.HTP_R.geometry}
      material={gltf.materials.wing}
      position={[-1.21, -0.57, -2.91]}
      rotation={[3.06, -0.03, 1.58]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Propeller.geometry}
      material={gltf.materials['Material.001']}
      position={[0.18, 0.09, 3.88]}
      scale={0}
    />
    <T.Mesh
      geometry={gltf.nodes.Rudder.geometry}
      material={gltf.materials.white}
      position={[-0.11, 0.51, -3.16]}
      rotation={[1.84, 1.56, -1.94]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Servo_holder_Wing.geometry}
      material={gltf.materials.wing}
      position={[-1.51, 0.23, 1.48]}
      rotation={[2.1, 1.52, -2.22]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Servo_holder_Wing001.geometry}
      material={gltf.materials.wing}
      position={[1.61, 0.2, 1.37]}
      rotation={[0.62, -1.53, 0.73]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Spinner1.geometry}
      material={gltf.materials.wing}
      position={[0.08, 0.09, 3.95]}
      rotation={[1.47, -0.01, -0.02]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.VTP.geometry}
      material={gltf.materials.wing}
      position={[-0.08, 0.39, -2.72]}
      rotation={[3.04, -0.03, -3.13]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Wing2L.geometry}
      material={gltf.materials.white}
      position={[3.51, 0.3, 1.34]}
      rotation={[3.03, -0.03, -1.57]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Wing2R.geometry}
      material={gltf.materials.white}
      position={[-3.4, 0.37, 1.53]}
      rotation={[3.04, -0.03, 1.59]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Wing3L.geometry}
      material={gltf.materials.wing}
      position={[4.73, 0.37, 0.69]}
      rotation={[3.04, -0.03, -1.59]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Wing3R.geometry}
      material={gltf.materials.wing}
      position={[-4.66, 0.46, 0.94]}
      rotation={[3.04, -0.02, 1.57]}
      scale={0.01}
    />
    <T.Mesh
      geometry={gltf.nodes.Wing_C.geometry}
      material={gltf.materials.white}
      position={[0.07, 0.13, 1.25]}
      rotation={[3.07, -0.03, -1.56]}
      scale={0.01}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
