<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 .\dji_less.glb --transform
-->

<script>
  import { Group } from 'three'

  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations, useDraco } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  ref = new Group()

  const dracoLoader = useDraco();
  const gltf = useGltf('3d/dji_less-transformed.glb', {dracoLoader})

  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  //Animation
  $effect(() => {
    $actions["TR-Spin"]?.play();
    $actions["TL-Spin"]?.play();
    $actions["BL-Spin"]?.play();
    $actions["BR-Spin"]?.play();
  })

</script>

<T
  is={ref}
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="UNT">
        <T.Group name="WM260">
          <T.Group
            name="BL-wing"
            position={[16.09, 1.08, -9.83]}
            rotation={[-0.05, -0.26, -0.13]}
          >
            <T.Group
              name="桨叶1"
              position={[0.01, 0.55, -0.01]}
              rotation={[3.12, -0.26, -3.02]}
            >
              <T.Group
                name="PROP1"
                position={[2.28, 0.53, 5.84]}
              >
                <T.Mesh
                  name="Prop1"
                  geometry={gltf.nodes.Prop1.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="PROP2"
                position={[-2.09, 0.73, -5.86]}
              >
                <T.Mesh
                  name="Prop2"
                  geometry={gltf.nodes.Prop2.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶1_01"
                position={[-0.1, -0.82, 0.01]}
              >
                <T.Mesh
                  name="桨叶1_01001"
                  geometry={gltf.nodes.桨叶1_01001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶1_02"
                position={[-0.04, -0.3, 0.01]}
              >
                <T.Mesh
                  name="桨叶1_02001"
                  geometry={gltf.nodes.桨叶1_02001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶1_03"
                position={[-0.22, 0.65, -0.86]}
              >
                <T.Mesh
                  name="桨叶1_03001"
                  geometry={gltf.nodes.桨叶1_03001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶1_04"
                position={[0.39, 0.6, 0.83]}
              >
                <T.Mesh
                  name="桨叶1_04001"
                  geometry={gltf.nodes.桨叶1_04001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶1_06"
                position={[-0.03, -0.25, 0.01]}
              >
                <T.Mesh
                  name="桨叶1_06001"
                  geometry={gltf.nodes.桨叶1_06001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶1_08"
                position={[0.03, 0.48, -0.01]}
              >
                <T.Mesh
                  name="Prop3"
                  geometry={gltf.nodes.Prop3.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶1_09"
                position={[-0.02, -0.14, 0]}
              >
                <T.Mesh
                  name="桨叶1_09001"
                  geometry={gltf.nodes.桨叶1_09001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group name="桨叶1_10">
                <T.Mesh
                  name="桨叶1_10001"
                  geometry={gltf.nodes.桨叶1_10001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group
            name="BR-wing"
            position={[-16.09, 1.07, -9.83]}
            rotation={[-0.39, 1.23, 0.4]}
          >
            <T.Group
              name="桨叶3"
              position={[0.03, 1.05, -0.01]}
              rotation={[0.02, 0.26, -0.13]}
            >
              <T.Group
                name="桨叶3_01"
                position={[0.13, -1.3, 0.02]}
                rotation={[2.55, -1.33, 2.57]}
              >
                <T.Mesh
                  name="桨叶3_01001"
                  geometry={gltf.nodes.桨叶3_01001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_02"
                position={[0.05, -0.61, 0.01]}
              >
                <T.Mesh
                  name="桨叶3_02001"
                  geometry={gltf.nodes.桨叶3_02001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_03"
                position={[0.07, -0.78, 0.02]}
              >
                <T.Mesh
                  name="桨叶3_03001"
                  geometry={gltf.nodes.桨叶3_03001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_04"
                position={[0.03, -0.48, 0.01]}
              >
                <T.Mesh
                  name="桨叶3_04001"
                  geometry={gltf.nodes.桨叶3_04001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_05"
                position={[0.25, 0.17, -0.85]}
              >
                <T.Mesh
                  name="桨叶3_05001"
                  geometry={gltf.nodes.桨叶3_05001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_06"
                position={[-0.36, 0.12, 0.84]}
              >
                <T.Mesh
                  name="桨叶3_06001"
                  geometry={gltf.nodes.桨叶3_06001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_07"
                position={[0.07, -0.73, 0.02]}
              >
                <T.Mesh
                  name="桨叶3_07001"
                  geometry={gltf.nodes.桨叶3_07001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶3_08"
                position={[-2.24, 0.05, 5.85]}
              >
                <T.Mesh
                  name="桨叶3_08001"
                  geometry={gltf.nodes.桨叶3_08001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶3_09"
                position={[2.12, 0.25, -5.85]}
              >
                <T.Mesh
                  name="桨叶3_09001"
                  geometry={gltf.nodes.桨叶3_09001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group name="桨叶3_10">
                <T.Mesh
                  name="桨叶3_10001"
                  geometry={gltf.nodes.桨叶3_10001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group
            name="TL-wing"
            position={[12.75, 0.39, 14.41]}
            rotation={[0.14, 0.86, -0.22]}
          >
            <T.Group
              name="桨叶4"
              position={[-0.56, 1.25, -6.24]}
              rotation={[3.1, -0.91, -3.03]}
            >
              <T.Group
                name="桨叶4_01"
                position={[4.3, -2.26, -4.23]}
              >
                <T.Mesh
                  name="桨叶4_01001"
                  geometry={gltf.nodes.桨叶4_01001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_02"
                position={[4.4, -1.58, -4.25]}
              >
                <T.Mesh
                  name="桨叶4_02001"
                  geometry={gltf.nodes.桨叶4_02001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_03"
                position={[4.37, -1.74, -4.24]}
              >
                <T.Mesh
                  name="桨叶4_03001"
                  geometry={gltf.nodes.桨叶4_03001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_04"
                position={[4.42, -1.43, -4.25]}
              >
                <T.Mesh
                  name="桨叶4_04001"
                  geometry={gltf.nodes.桨叶4_04001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_05"
                position={[3.87, -0.71, -3.65]}
              >
                <T.Mesh
                  name="桨叶4_05001"
                  geometry={gltf.nodes.桨叶4_05001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_06"
                position={[5.16, -0.93, -4.89]}
              >
                <T.Mesh
                  name="桨叶4_06001"
                  geometry={gltf.nodes.桨叶4_06001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_07"
                position={[4.48, -0.98, -4.26]}
              >
                <T.Mesh
                  name="桨叶4_07001"
                  geometry={gltf.nodes.桨叶4_07001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶4_08"
                position={[4.5, -0.91, -4.27]}
              >
                <T.Mesh
                  name="桨叶4_08001"
                  geometry={gltf.nodes.桨叶4_08001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶4_09"
                position={[9.06, -1.38, -8.54]}
              >
                <T.Mesh
                  name="桨叶4_09001"
                  geometry={gltf.nodes.桨叶4_09001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group name="桨叶4_10">
                <T.Mesh
                  name="桨叶4_10001"
                  geometry={gltf.nodes.桨叶4_10001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group
            name="TR-wing"
            position={[-12.75, 0.38, 14.41]}
            rotation={[-1.65, 1.45, Math.PI / 2]}
          >
            <T.Group
              name="桨叶2"
              position={[-2.65, 1.4, -5.68]}
              rotation={[0.03, -0.39, -0.13]}
            >
              <T.Group
                name="桨叶2_01"
                position={[4.76, -0.88, 4.31]}
              >
                <T.Mesh
                  name="桨叶2_01001"
                  geometry={gltf.nodes.桨叶2_01001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_02"
                position={[4.69, -0.36, 4.3]}
              >
                <T.Mesh
                  name="桨叶2_02001"
                  geometry={gltf.nodes.桨叶2_02001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_03"
                position={[4.66, -0.2, 4.29]}
              >
                <T.Mesh
                  name="桨叶2_03001"
                  geometry={gltf.nodes.桨叶2_03001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_04"
                position={[4.64, -0.05, 4.29]}
              >
                <T.Mesh
                  name="桨叶2_04001"
                  geometry={gltf.nodes.桨叶2_04001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_05"
                position={[5.19, 0.67, 4.89]}
              >
                <T.Mesh
                  name="桨叶2_05001"
                  geometry={gltf.nodes.桨叶2_05001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_06"
                position={[3.9, 0.45, 3.65]}
              >
                <T.Mesh
                  name="桨叶2_06001"
                  geometry={gltf.nodes.桨叶2_06001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_07"
                position={[4.58, 0.39, 4.28]}
              >
                <T.Mesh
                  name="桨叶2_07001"
                  geometry={gltf.nodes.桨叶2_07001.geometry}
                  material={gltf.materials.Material_0}
                />
              </T.Group>
              <T.Group
                name="桨叶2_08"
                position={[4.56, 0.46, 4.27]}
              >
                <T.Mesh
                  name="桨叶2_08001"
                  geometry={gltf.nodes.桨叶2_08001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group
                name="桨叶2_09"
                position={[9.06, 1.38, 8.54]}
              >
                <T.Mesh
                  name="桨叶2_09001"
                  geometry={gltf.nodes.桨叶2_09001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
              <T.Group name="桨叶2_10">
                <T.Mesh
                  name="桨叶2_10001"
                  geometry={gltf.nodes.桨叶2_10001.geometry}
                  material={gltf.materials['UNT Material']}
                />
              </T.Group>
            </T.Group>
          </T.Group>
          <T.Group
            name="black"
            position={[0, -0.91, 0.59]}
          >
            <T.Mesh
              name="black001"
              geometry={gltf.nodes.black001.geometry}
              material={gltf.materials.Material_0}
            />
          </T.Group>
          <T.Group
            name="JT"
            position={[0, 0.61, -10.57]}
          >
            <T.Group
              name="JT_01"
              position={[0, 1.43, 2.27]}
            >
              <T.Mesh
                name="JT_01001"
                geometry={gltf.nodes.JT_01001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="JT_02"
              position={[0, 1.73, 2.01]}
            >
              <T.Mesh
                name="JT_02001"
                geometry={gltf.nodes.JT_02001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_03"
              position={[0, 1.18, 2.35]}
            >
              <T.Mesh
                name="JT_03001"
                geometry={gltf.nodes.JT_03001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_04"
              position={[0, 0.03, 1.56]}
            >
              <T.Mesh
                name="JT_04001"
                geometry={gltf.nodes.JT_04001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_05"
              position={[0, -0.61, 10.57]}
            >
              <T.Mesh
                name="JT_05001"
                geometry={gltf.nodes.JT_05001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_06"
              position={[0, -0.61, 10.57]}
            >
              <T.Mesh
                name="JT_06001"
                geometry={gltf.nodes.JT_06001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_07"
              position={[0, -0.61, 10.57]}
            >
              <T.Mesh
                name="JT_07001"
                geometry={gltf.nodes.JT_07001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_08"
              position={[0.04, -0.25, -1.62]}
            >
              <T.Mesh
                name="JT_08001"
                geometry={gltf.nodes.JT_08001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_09"
              position={[0.13, -0.21, -1.39]}
            >
              <T.Mesh
                name="JT_09001"
                geometry={gltf.nodes.JT_09001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_10"
              position={[0, 0.2, -1.9]}
            >
              <T.Mesh
                name="JT_10001"
                geometry={gltf.nodes.JT_10001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="JT_13"
              position={[-0.02, 0.02, 0.56]}
            >
              <T.Mesh
                name="JT_13001"
                geometry={gltf.nodes.JT_13001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="JT_14"
              position={[0, 0.03, 0.97]}
            >
              <T.Mesh
                name="JT_14001"
                geometry={gltf.nodes.JT_14001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group name="JT_15">
              <T.Mesh
                name="JT_15001"
                geometry={gltf.nodes.JT_15001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="JT_glass"
              position={[0.04, 0.28, -1.9]}
            >
              <T.Mesh
                name="JT_glass001"
                geometry={gltf.nodes.JT_glass001.geometry}
                material={gltf.materials.Material_1}
              />
            </T.Group>
            <T.Group
              name="挤压_1"
              position={[-0.19, 1.29, -1.88]}
            >
              <T.Mesh
                name="挤压_1001"
                geometry={gltf.nodes.挤压_1001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="球体"
              position={[0, -0.21, -1.13]}
            >
              <T.Mesh
                name="球体001"
                geometry={gltf.nodes.球体001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="球体_2"
              position={[-0.51, 1.26, -1.44]}
            >
              <T.Mesh
                name="球体_2001"
                geometry={gltf.nodes.球体_2001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
          </T.Group>
          <T.Group
            name="机身"
            position={[-0.09, 1.32, 5.75]}
          >
            <T.Group
              name="机身_01"
              position={[0.09, -1.32, -5.75]}
              rotation={[-Math.PI, 0, 0]}
              scale={-1}
            >
              <T.Mesh
                name="机身_01001"
                geometry={gltf.nodes.机身_01001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_02"
              position={[0.09, -1.32, -5.75]}
            >
              <T.Mesh
                name="机身_02001"
                geometry={gltf.nodes.机身_02001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_03"
              position={[3.86, -0.77, 0.38]}
            >
              <T.Mesh
                name="机身_03001"
                geometry={gltf.nodes.机身_03001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_04"
              position={[-16.42, -2.85, -16]}
            >
              <T.Mesh
                name="机身_04001"
                geometry={gltf.nodes.机身_04001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_05"
              position={[-16.52, -2.66, -16.07]}
            >
              <T.Mesh
                name="机身_05001"
                geometry={gltf.nodes.机身_05001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_06"
              position={[-16.62, -2.46, -16.14]}
            >
              <T.Mesh
                name="机身_06001"
                geometry={gltf.nodes.机身_06001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_07"
              position={[-16.55, -2.72, -16.09]}
            >
              <T.Mesh
                name="机身_07001"
                geometry={gltf.nodes.机身_07001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_08"
              position={[-16, -0.31, -15.58]}
            >
              <T.Mesh
                name="机身_08001"
                geometry={gltf.nodes.机身_08001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_09"
              position={[-10.72, -0.38, -14.31]}
            >
              <T.Mesh
                name="机身_09001"
                geometry={gltf.nodes.机身_09001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_10"
              position={[-14.41, -5.65, -15.03]}
            >
              <T.Mesh
                name="机身_10001"
                geometry={gltf.nodes.机身_10001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_11"
              position={[-16.11, -0.87, -15.57]}
            >
              <T.Mesh
                name="机身_11001"
                geometry={gltf.nodes.机身_11001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_12"
              position={[-16.47, -2.63, -16.03]}
            >
              <T.Mesh
                name="机身_12001"
                geometry={gltf.nodes.机身_12001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_13"
              position={[-13.47, -1.3, -14.14]}
            >
              <T.Mesh
                name="机身_13001"
                geometry={gltf.nodes.机身_13001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_14"
              position={[-15.45, -3.75, -15.57]}
            >
              <T.Mesh
                name="机身_14001"
                geometry={gltf.nodes.机身_14001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_15"
              position={[-4.46, 1.12, -11.46]}
            >
              <T.Mesh
                name="机身_15001"
                geometry={gltf.nodes.机身_15001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_16"
              position={[-3.28, 1.33, -11.1]}
            >
              <T.Mesh
                name="机身_16001"
                geometry={gltf.nodes.机身_16001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_17"
              position={[16.59, -2.85, -16]}
            >
              <T.Mesh
                name="机身_17001"
                geometry={gltf.nodes.机身_17001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_18"
              position={[16.69, -2.66, -16.07]}
            >
              <T.Mesh
                name="机身_18001"
                geometry={gltf.nodes.机身_18001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_19"
              position={[16.79, -2.46, -16.14]}
            >
              <T.Mesh
                name="机身_19001"
                geometry={gltf.nodes.机身_19001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_20"
              position={[4.63, 1.12, -11.46]}
            >
              <T.Mesh
                name="机身_20001"
                geometry={gltf.nodes.机身_20001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_21"
              position={[16.17, -0.31, -15.58]}
            >
              <T.Mesh
                name="机身_21001"
                geometry={gltf.nodes.机身_21001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_22"
              position={[10.89, -0.38, -14.31]}
            >
              <T.Mesh
                name="机身_22001"
                geometry={gltf.nodes.机身_22001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_23"
              position={[14.58, -5.65, -15.03]}
            >
              <T.Mesh
                name="机身_23001"
                geometry={gltf.nodes.机身_23001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_24"
              position={[16.28, -0.87, -15.57]}
            >
              <T.Mesh
                name="机身_24001"
                geometry={gltf.nodes.机身_24001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_25"
              position={[16.64, -2.63, -16.03]}
            >
              <T.Mesh
                name="机身_25001"
                geometry={gltf.nodes.机身_25001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_26"
              position={[13.64, -1.3, -14.14]}
            >
              <T.Mesh
                name="机身_26001"
                geometry={gltf.nodes.机身_26001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_27"
              position={[15.62, -3.75, -15.57]}
            >
              <T.Mesh
                name="机身_27001"
                geometry={gltf.nodes.机身_27001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_28"
              position={[16.72, -2.72, -16.09]}
            >
              <T.Mesh
                name="机身_28001"
                geometry={gltf.nodes.机身_28001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_29"
              position={[3.45, 1.33, -11.1]}
            >
              <T.Mesh
                name="机身_29001"
                geometry={gltf.nodes.机身_29001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_30"
              position={[0.09, 4.37, -15.82]}
            >
              <T.Mesh
                name="机身_30001"
                geometry={gltf.nodes.机身_30001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_31"
              position={[3.34, 0.03, -10.87]}
            >
              <T.Mesh
                name="机身_31001"
                geometry={gltf.nodes.机身_31001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_32"
              position={[3.15, 3.41, -17.06]}
            >
              <T.Mesh
                name="机身_32001"
                geometry={gltf.nodes.机身_32001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_33"
              position={[3.25, 3.4, -17.17]}
            >
              <T.Mesh
                name="机身_33001"
                geometry={gltf.nodes.机身_33001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_34"
              position={[2.1, 3.99, -1.04]}
            >
              <T.Mesh
                name="机身_34001"
                geometry={gltf.nodes.机身_34001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_35"
              position={[0.09, 3.95, -2.86]}
            >
              <T.Mesh
                name="机身_35001"
                geometry={gltf.nodes.机身_35001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_36"
              position={[0.09, 0.58, -7.82]}
            >
              <T.Mesh
                name="机身_36001"
                geometry={gltf.nodes.机身_36001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_37"
              position={[0.08, 0.57, 1.66]}
            >
              <T.Mesh
                name="机身_37001"
                geometry={gltf.nodes.机身_37001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_38"
              position={[0.09, 3.92, -9.7]}
            >
              <T.Mesh
                name="机身_38001"
                geometry={gltf.nodes.机身_38001.geometry}
                material={gltf.materials['UNT Material']}
                position={[0, -0.04, 0]}
              />
            </T.Group>
            <T.Group
              name="机身_39"
              position={[-2.26, 1.84, 0.77]}
            >
              <T.Mesh
                name="机身_39001"
                geometry={gltf.nodes.机身_39001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_40"
              position={[-2.46, 1.83, 0.83]}
            >
              <T.Mesh
                name="机身_40001"
                geometry={gltf.nodes.机身_40001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_41"
              position={[2.63, 1.83, 0.83]}
            >
              <T.Mesh
                name="机身_41001"
                geometry={gltf.nodes.机身_41001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_42"
              position={[0.09, 3.81, -2.09]}
            >
              <T.Mesh
                name="机身_42001"
                geometry={gltf.nodes.机身_42001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_43"
              position={[0.09, 3.38, -17.17]}
            >
              <T.Mesh
                name="机身_43001"
                geometry={gltf.nodes.机身_43001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_44"
              position={[2.43, 1.84, 0.77]}
            >
              <T.Mesh
                name="机身_44001"
                geometry={gltf.nodes.机身_44001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_45"
              position={[0.09, 3.22, 1.28]}
            >
              <T.Mesh
                name="机身_45001"
                geometry={gltf.nodes.机身_45001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_46"
              position={[-0.88, 0.71, 1.94]}
            >
              <T.Mesh
                name="机身_46001"
                geometry={gltf.nodes.机身_46001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_47"
              position={[-0.31, 0.71, 1.95]}
            >
              <T.Mesh
                name="机身_47001"
                geometry={gltf.nodes.机身_47001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_48"
              position={[0.27, 0.71, 1.95]}
            >
              <T.Mesh
                name="机身_48001"
                geometry={gltf.nodes.机身_48001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_49"
              position={[-1.45, 0.71, 1.89]}
            >
              <T.Mesh
                name="机身_49001"
                geometry={gltf.nodes.机身_49001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_50"
              position={[-3.17, 0.03, -10.87]}
            >
              <T.Mesh
                name="机身_50001"
                geometry={gltf.nodes.机身_50001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_51"
              position={[-1.93, 3.99, -1.04]}
            >
              <T.Mesh
                name="机身_51001"
                geometry={gltf.nodes.机身_51001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_52"
              position={[0.09, 3.05, -0.66]}
            >
              <T.Mesh
                name="机身_52001"
                geometry={gltf.nodes.机身_52001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_53"
              position={[-2.57, 3.44, 0.75]}
            >
              <T.Mesh
                name="机身_53001"
                geometry={gltf.nodes.机身_53001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_54"
              position={[0.09, -2.19, -4.8]}
            >
              <T.Mesh
                name="机身_54001"
                geometry={gltf.nodes.机身_54001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_55"
              position={[0.09, -2.71, -8.77]}
            >
              <T.Mesh
                name="机身_55001"
                geometry={gltf.nodes.机身_55001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_56"
              position={[2.74, 3.44, 0.75]}
            >
              <T.Mesh
                name="机身_56001"
                geometry={gltf.nodes.机身_56001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_57"
              position={[2.63, 3.44, 0.64]}
            >
              <T.Mesh
                name="机身_57001"
                geometry={gltf.nodes.机身_57001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_58"
              position={[-3.08, 3.4, -17.17]}
            >
              <T.Mesh
                name="机身_58001"
                geometry={gltf.nodes.机身_58001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_59"
              position={[-2.98, 3.41, -17.06]}
            >
              <T.Mesh
                name="机身_59001"
                geometry={gltf.nodes.机身_59001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_60"
              position={[1.29, 0.71, 1.96]}
            >
              <T.Mesh
                name="机身_60001"
                geometry={gltf.nodes.机身_60001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_61"
              position={[0.09, -2.54, -2.3]}
            >
              <T.Mesh
                name="机身_61001"
                geometry={gltf.nodes.机身_61001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_62"
              position={[0.08, -2.7, -6.8]}
            >
              <T.Mesh
                name="机身_62001"
                geometry={gltf.nodes.机身_62001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_63"
              position={[0.08, -2.7, -2.3]}
            >
              <T.Mesh
                name="机身_63001"
                geometry={gltf.nodes.机身_63001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_64"
              position={[0.08, -2.54, -6.8]}
            >
              <T.Mesh
                name="机身_64001"
                geometry={gltf.nodes.机身_64001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_65"
              position={[-2.46, 3.44, 0.64]}
            >
              <T.Mesh
                name="机身_65001"
                geometry={gltf.nodes.机身_65001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_66"
              position={[0.09, -2.2, -10.23]}
            >
              <T.Mesh
                name="机身_66001"
                geometry={gltf.nodes.机身_66001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_67"
              position={[1.8, -2.6, -1.14]}
            >
              <T.Mesh
                name="机身_67001"
                geometry={gltf.nodes.机身_67001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_68"
              position={[-2.83, 1, -0.38]}
            >
              <T.Mesh
                name="机身_68001"
                geometry={gltf.nodes.机身_68001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_69"
              position={[3, 1, -0.38]}
            >
              <T.Mesh
                name="机身_69001"
                geometry={gltf.nodes.机身_69001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_70"
              position={[-1.63, -2.6, -1.14]}
            >
              <T.Mesh
                name="机身_70001"
                geometry={gltf.nodes.机身_70001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_71"
              position={[-12.43, -2.99, 8.71]}
            >
              <T.Mesh
                name="机身_71001"
                geometry={gltf.nodes.机身_71001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_72"
              position={[-13.15, -2.95, 9.41]}
            >
              <T.Mesh
                name="机身_72001"
                geometry={gltf.nodes.机身_72001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_73"
              position={[-13.29, -2.98, 9.53]}
            >
              <T.Mesh
                name="机身_73001"
                geometry={gltf.nodes.机身_73001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_74"
              position={[-9.07, -1.63, 4.87]}
            >
              <T.Mesh
                name="机身_74001"
                geometry={gltf.nodes.机身_74001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_75"
              position={[-12.92, -3.78, 8.98]}
            >
              <T.Mesh
                name="机身_75001"
                geometry={gltf.nodes.机身_75001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_76"
              position={[-12.55, -1.52, 8.68]}
            >
              <T.Mesh
                name="机身_76001"
                geometry={gltf.nodes.机身_76001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_77"
              position={[-13.16, -3.17, 9.45]}
            >
              <T.Mesh
                name="机身_77001"
                geometry={gltf.nodes.机身_77001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_78"
              position={[-13.25, -2.73, 9.47]}
            >
              <T.Mesh
                name="机身_78001"
                geometry={gltf.nodes.机身_78001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_79"
              position={[-13.21, -2.95, 9.46]}
            >
              <T.Mesh
                name="机身_79001"
                geometry={gltf.nodes.机身_79001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_80"
              position={[-3.69, -0.77, 0.38]}
            >
              <T.Mesh
                name="机身_80001"
                geometry={gltf.nodes.机身_80001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_81"
              position={[13.33, -3.17, 9.45]}
            >
              <T.Mesh
                name="机身_81001"
                geometry={gltf.nodes.机身_81001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_82"
              position={[13.42, -2.73, 9.47]}
            >
              <T.Mesh
                name="机身_82001"
                geometry={gltf.nodes.机身_82001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_83"
              position={[13.38, -2.95, 9.46]}
            >
              <T.Mesh
                name="机身_83001"
                geometry={gltf.nodes.机身_83001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_84"
              position={[12.6, -2.99, 8.71]}
            >
              <T.Mesh
                name="机身_84001"
                geometry={gltf.nodes.机身_84001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_85"
              position={[13.32, -2.95, 9.41]}
            >
              <T.Mesh
                name="机身_85001"
                geometry={gltf.nodes.机身_85001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_86"
              position={[13.46, -2.98, 9.53]}
            >
              <T.Mesh
                name="机身_86001"
                geometry={gltf.nodes.机身_86001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_87"
              position={[9.24, -1.63, 4.87]}
            >
              <T.Mesh
                name="机身_87001"
                geometry={gltf.nodes.机身_87001.geometry}
                material={gltf.materials['UNT Material']}
              />
            </T.Group>
            <T.Group
              name="机身_88"
              position={[13.09, -3.78, 8.98]}
            >
              <T.Mesh
                name="机身_88001"
                geometry={gltf.nodes.机身_88001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
            <T.Group
              name="机身_89"
              position={[12.72, -1.52, 8.68]}
            >
              <T.Mesh
                name="机身_89001"
                geometry={gltf.nodes.机身_89001.geometry}
                material={gltf.materials.Material_0}
              />
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T>
